import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

interface LineItemPDF {
  description: string | null;
  quantity: number;
  rate: number;
  subtotal: number;
}
interface InvoicePDFInput {
  invoiceNumber: string;
  status: string;
  issueDate: string;
  dueDate: string | null;
  clientName: string;
  clientCompany?: string | null;
  clientEmail?: string | null;
  ownerName: string;
  items: LineItemPDF[];
  subtotal: number;
  tax: number;
  discount: number;
  total: number;
  paymentNotes?: string | null;
}

const ACCENT = rgb(16 / 255, 185 / 255, 129 / 255);
const INK = rgb(28 / 255, 25 / 255, 23 / 255);
const SOFT = rgb(120 / 255, 113 / 255, 108 / 255);

export async function buildInvoicePdf(d: InvoicePDFInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();

  let y = height - 56;
  // Header
  page.drawText("Briefly", { x: 56, y, size: 22, font: bold, color: ACCENT });
  page.drawText("INVOICE", { x: width - 56 - bold.widthOfTextAtSize("INVOICE", 16), y, size: 16, font: bold, color: INK });
  y -= 26;
  page.drawText(`#${d.invoiceNumber}`, { x: width - 56 - font.widthOfTextAtSize(`#${d.invoiceNumber}`, 11), y, size: 11, font, color: SOFT });
  y -= 40;

  // From / To
  page.drawText("From", { x: 56, y, size: 10, font: bold, color: SOFT });
  page.drawText(d.ownerName, { x: 56, y: y - 14, size: 12, font: bold, color: INK });
  page.drawText("Bill to", { x: 300, y, size: 10, font: bold, color: SOFT });
  page.drawText(d.clientName, { x: 300, y: y - 14, size: 12, font: bold, color: INK });
  if (d.clientCompany) page.drawText(d.clientCompany, { x: 300, y: y - 28, size: 10, font, color: INK });
  if (d.clientEmail) page.drawText(d.clientEmail, { x: 300, y: y - 42, size: 10, font, color: SOFT });
  y -= 70;

  // Dates
  page.drawText(`Issued: ${d.issueDate}`, { x: 56, y, size: 10, font, color: INK });
  page.drawText(`Due: ${d.dueDate ?? "—"}`, { x: 200, y, size: 10, font, color: INK });
  y -= 30;

  // Table header
  const left = 56;
  const cols = { desc: left, qty: 340, rate: 400, amt: 500 };
  page.drawRectangle({ x: left, y: y - 6, width: width - left * 2, height: 26, color: rgb(250 / 255, 250 / 255, 249 / 255) });
  page.drawText("Description", { x: cols.desc, y: y, size: 10, font: bold, color: SOFT });
  page.drawText("Qty", { x: cols.qty, y: y, size: 10, font: bold, color: SOFT });
  page.drawText("Rate", { x: cols.rate, y: y, size: 10, font: bold, color: SOFT });
  page.drawText("Amount", { x: cols.amt, y: y, size: 10, font: bold, color: SOFT });
  y -= 24;

  for (const it of d.items) {
    if (y < 120) break;
    const desc = (it.description || "—").slice(0, 46);
    page.drawText(desc, { x: cols.desc, y, size: 10, font, color: INK });
    page.drawText(String(it.quantity), { x: cols.qty, y, size: 10, font, color: INK });
    page.drawText(`$${it.rate.toFixed(2)}`, { x: cols.rate, y, size: 10, font, color: INK });
    page.drawText(`$${it.subtotal.toFixed(2)}`, { x: cols.amt, y, size: 10, font, color: INK });
    y -= 20;
  }
  y -= 16;
  page.drawLine({ start: { x: left, y }, end: { x: width - left, y }, thickness: 1, color: rgb(231 / 255, 229 / 255, 228 / 255) });
  y -= 22;

  const right = width - left;
  const labelX = right - 160;
  const valX = right - 60;
  page.drawText("Subtotal", { x: labelX, y, size: 10, font, color: SOFT });
  page.drawText(`$${d.subtotal.toFixed(2)}`, { x: valX, y, size: 10, font, color: INK });
  y -= 18;
  page.drawText("Tax", { x: labelX, y, size: 10, font, color: SOFT });
  page.drawText(`$${d.tax.toFixed(2)}`, { x: valX, y, size: 10, font, color: INK });
  y -= 18;
  page.drawText("Discount", { x: labelX, y, size: 10, font, color: SOFT });
  page.drawText(`$${d.discount.toFixed(2)}`, { x: valX, y, size: 10, font, color: INK });
  y -= 22;
  page.drawText("Total", { x: labelX, y, size: 12, font: bold, color: INK });
  page.drawText(`$${d.total.toFixed(2)}`, { x: valX, y, size: 12, font: bold, color: ACCENT });

  if (d.paymentNotes) {
    y -= 44;
    page.drawText("Notes", { x: left, y, size: 10, font: bold, color: SOFT });
    const lines = wrap(d.paymentNotes, 90);
    y -= 16;
    for (const line of lines.slice(0, 6)) {
      page.drawText(line, { x: left, y, size: 9, font, color: INK });
      y -= 13;
    }
  }

  page.drawText(`${d.ownerName} · Generated by Briefly`, { x: left, y: 56, size: 9, font, color: SOFT });

  return pdf.save();
}

function wrap(text: string, max: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if ((cur + " " + w).trim().length > max) {
      lines.push(cur.trim());
      cur = w;
    } else {
      cur += " " + w;
    }
  }
  if (cur.trim()) lines.push(cur.trim());
  return lines;
}
