import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

interface ProposalPDFInput {
  title: string;
  clientName: string;
  clientCompany?: string | null;
  ownerName: string;
  scope?: string | null;
  timeline?: string | null;
  pricing?: string | null;
  terms?: string | null;
  items: { description: string | null; amount: number }[];
}

const ACCENT = rgb(16 / 255, 185 / 255, 129 / 255);
const INK = rgb(28 / 255, 25 / 255, 23 / 255);
const SOFT = rgb(120 / 255, 113 / 255, 108 / 255);

function wrap(text: string, max: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if ((cur + " " + w).trim().length > max) {
      lines.push(cur.trim());
      cur = w;
    } else cur += " " + w;
  }
  if (cur.trim()) lines.push(cur.trim());
  return lines;
}

export async function buildProposalPdf(d: ProposalPDFInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();
  let y = height - 56;

  page.drawText("Briefly", { x: 56, y, size: 22, font: bold, color: ACCENT });
  page.drawText("PROPOSAL", { x: width - 56 - bold.widthOfTextAtSize("PROPOSAL", 16), y, size: 16, font: bold, color: INK });
  y -= 36;
  page.drawText(d.title, { x: 56, y, size: 16, font: bold, color: INK });
  y -= 24;
  page.drawText(`Prepared for ${d.clientName}${d.clientCompany ? " · " + d.clientCompany : ""}`, { x: 56, y, size: 10, font, color: SOFT });
  y -= 30;

  const sections: { label: string; body?: string | null }[] = [
    { label: "Scope of Work", body: d.scope },
    { label: "Timeline", body: d.timeline },
    { label: "Pricing", body: d.pricing },
    { label: "Terms & Conditions", body: d.terms },
  ];

  for (const s of sections) {
    if (!s.body) continue;
    page.drawText(s.label, { x: 56, y, size: 11, font: bold, color: INK });
    y -= 16;
    for (const line of wrap(s.body, 95).slice(0, 12)) {
      page.drawText(line, { x: 56, y, size: 10, font, color: SOFT });
      y -= 14;
    }
    y -= 14;
  }

  if (d.items.length) {
    page.drawText("Investment", { x: 56, y, size: 11, font: bold, color: INK });
    y -= 16;
    let total = 0;
    for (const it of d.items) {
      total += it.amount;
      page.drawText(it.description || "—", { x: 56, y, size: 10, font, color: INK });
      page.drawText(`$${it.amount.toFixed(2)}`, { x: width - 120, y, size: 10, font, color: INK });
      y -= 16;
    }
    y -= 6;
    page.drawText("Total", { x: 56, y, size: 11, font: bold, color: INK });
    page.drawText(`$${total.toFixed(2)}`, { x: width - 120, y, size: 11, font: bold, color: ACCENT });
  }

  page.drawText(`${d.ownerName} · Generated by Briefly`, { x: 56, y: 56, size: 9, font, color: SOFT });
  return pdf.save();
}
